config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :courses
  resources :students do
    collection do
      get :autocomplete_student_name
    end
  end
  resources :classrooms

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  validates :student_id, presence: true
  validates :course_id, presence: true

  belongs_to :student
  belongs_to :course

  before_create :set_entry_at

  def set_entry_at
    self.entry_at = Time.now
  end

  def student_name
    s = Student.find(self.student_id) if self.student_id
    s.name if s
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 45 }
  validates :description, presence: true, length: { maximum: 45 }
  validates :status, presence: true
  has_enumeration_for :status, with: CourseStatus
  has_many :classrooms, dependent: :restrict_with_error
end

app/models/course_status.rb
class CourseStatus < EnumerateIt::Base
  associate_values active: 1, inactive: 2
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 45 }
  validates :register_number, presence: true, length: { maximum: 45 }
  validates :status, presence: true

  has_enumeration_for :status, with: StudentStatus

  has_many :classrooms, dependent: :restrict_with_error

end

app/models/student_status.rb
class StudentStatus < EnumerateIt::Base
  associate_values active: 1, inactive: 2
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_filter :set_classroom, only: [:edit, :update, :destroy]
  def index
    @classrooms = Classroom.all.includes(:student, :course)
  end

  def new
    @classroom = Classroom.new
  end

  def edit
  end

  def show
    @classroom = Classroom.find(params[:id])
  end

  def create
    @classroom = Classroom.new(classroom_params)
    if @classroom.save
      redirect_to(@classroom, flash:{ notice: t('messages.save', model_name: t('activerecord.models.classroom'))  } )
    else
      render 'new'
    end
  end

  def update
    @classroom.assign_attributes(classroom_params)
    if @classroom.save
      redirect_to(@classroom)
    else
      render "edit"
    end
  end

  def destroy
    @classroom.destroy
    redirect_to classrooms_url
  end

  private

    def classroom_params
      params.require(:classroom).permit(:course_id, :student_id)
    end

    def set_classroom
      @classroom = Classroom.find(params[:id])
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :set_course, only: [:edit, :update, :destroy]
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def show
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to(@course, flash:{ notice: t('messages.save', model_name: t('activerecord.models.course'))  })
    else
      render 'new'
    end
  end

  def update
    @course.assign_attributes(course_params)
    if @course.save
      redirect_to(@course, flash:{ notice: t('messages.save', model_name: t('activerecord.models.course'))  } )
    else
      render "edit"
    end
  end

  def destroy
    if @course.destroy
      redirect_to(courses_url, flash:{ notice: t('messages.destroy', model_name: t('activerecord.models.course')) })
    else
      redirect_to(courses_url, flash:{ notice: t('messages.not_destroy', model_name: t('activerecord.models.course')) })
    end
  end

  private

    def course_params
      params.require(:course).permit(:name, :description, :status)
    end

    def set_course
      @course = Course.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_filter :set_student, only: [:edit, :update, :destroy]
  autocomplete :student, :name
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def show
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to(@student, flash:{ notice: t('messages.save', model_name: t('activerecord.models.student'))  } )
    else
      render 'new'
    end
  end

  def update
    @student.assign_attributes(student_params)
    if @student.save
      redirect_to(@student, flash:{ notice: t('messages.save', model_name: t('activerecord.models.student')) })
    else
      render "edit"
    end
  end

  def destroy
    if @student.destroy
      redirect_to(students_url, flash:{ notice: t('messages.destroy', model_name: t('activerecord.models.student')) })
    else
      redirect_to(students_url, flash:{ notice: t('messages.not_destroy', model_name: t('activerecord.models.student')) })
    end
  end

  private

    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end

    def set_student
      @student = Student.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      puts "#{key}"
      alert_class = case(key.to_sym)
      when :notice
        "success"
      when :error
        "danger"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert alert-#{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/index.html.haml
%h3= "#{t('labels.list')} #{t('activerecord.models.classrooms')}"
%p
  = link_to t('labels.new'), new_classroom_path, class:"btn btn-primary"

%table.table.table-striped
  %tr
    %th= t('activerecord.attributes.classroom.student_id')
    %th= t('activerecord.attributes.classroom.course_id')
    %th= t('activerecord.attributes.classroom.entry_at')
    %th
  - @classrooms.each do |classroom|
    %tr
      %td= classroom.student.name
      %td= classroom.course.name
      %td= classroom.entry_at.strftime('%d/%m/%Y %H:%M')
      %td
        = link_to t('labels.show'), classroom

app/views/classrooms/new.html.haml
%h3= "#{t('labels.new')} #{t('activerecord.models.classroom')}"
%p
  = link_to 'Voltar', classrooms_path, class:"btn btn-info"
%p
  = simple_form_for(@classroom) do |f|
    .row
      .col-md-5
        .form-group
          = f.input :course_id, collection: Course.all.order(:name), input_html: {class:"form-control"}
      .col-md-5
        .form-group
          = f.input :student_id, as: :hidden
          = f.input :student_name, url: autocomplete_student_name_students_path, as: :autocomplete, input_html: {class:"form-control", 'data-id-element' => '#classroom_student_id'}
    %br
    = f.submit t('labels.save'), class: 'btn btn-primary'

app/views/classrooms/show.html.haml
%h3= "#{t('labels.show')} #{t('activerecord.models.classroom')}"
%p
  = link_to 'Voltar', classrooms_path, class:"btn btn-info"
%p
  %label=t('activerecord.attributes.classroom.course_id')
  %p=@classroom.course.name
  %label=t('activerecord.attributes.classroom.student_id')
  %p=@classroom.student.name

app/views/courses/_form.html.haml
= simple_form_for(@course) do |f|
  .row
    .col-md-5
      .form-group
        = f.input :name, input_html: {disabled: readonly, class:"form-control"}
    .col-md-5
      .form-group
        = f.input :description, input_html: {disabled: readonly, class:"form-control"}
    .col-md-2
      .form-group
        = f.input :status, collection: CourseStatus.to_a, input_html: {disabled: readonly, class:"form-control"}
  - unless readonly
    %br
    = f.submit t('labels.save'), class: 'btn btn-primary'

app/views/courses/edit.html.haml
%h3= "#{t('labels.edit')} #{t('activerecord.models.course')}"
%p
  = link_to 'Voltar', courses_path, class:"btn btn-info"
%p
  = render 'form', readonly: false

app/views/courses/index.html.haml
%h3= "#{t('labels.list')} #{t('activerecord.models.courses')}"
%p
  = link_to t('labels.new'), new_course_path, class:"btn btn-primary"

%table.table.table-striped
  %tr
    %th= t('activerecord.attributes.course.name')
    %th= t('activerecord.attributes.course.description')
    %th= t('activerecord.attributes.course.status')
    %th
  - @courses.each do |course|
    %tr
      %td= course.name
      %td= course.description
      %td= course.status_humanize
      %td
        = link_to t('labels.show'), course
        = link_to t('labels.edit'), edit_course_path(course)
        = link_to t('labels.destroy'), course, method: :delete, data: { confirm: "Deseja excluir esse aluno?" }

app/views/courses/new.html.haml
%h3= "#{t('labels.new')} #{t('activerecord.models.course')}"
%p
  = link_to 'Voltar', courses_path, class:"btn btn-info"
%p
  = render 'form', readonly: false

app/views/courses/show.html.haml
%h3= "#{t('labels.show')} #{t('activerecord.models.course')}"
%p
  = link_to 'Voltar', courses_path, class:"btn btn-info"
%p
  = render 'form', readonly: true

app/views/home/index.html.haml
%p
  Selecione uma opção
= link_to t('activerecord.models.students'), students_path, class: 'btn btn-primary'
= link_to t('activerecord.models.courses'), courses_path, class: 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Projeto de teste', root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to t('labels.home'), root_path %>
          </li>
          <li>
            <%= link_to t('activerecord.models.students'), students_path %>
          </li>
          <li>
            <%= link_to t('activerecord.models.courses'), courses_path %>
          </li>
          <li>
            <%= link_to t('activerecord.models.classrooms'), classrooms_path %>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
  <div class="starter-template">
    <%= flash_messages %>
    <%= yield %>
  </div>


</body>
</html>

app/views/students/_form.html.haml
= simple_form_for(@student) do |f|
  .row
    .col-md-5
      .form-group
        = f.input :name, input_html: {disabled: readonly, class:"form-control"}
    .col-md-5
      .form-group
        = f.input :register_number, input_html: {disabled: readonly, class:"form-control"}
    .col-md-2
      .form-group
        = f.input :status, collection: StudentStatus.to_a, input_html: {disabled: readonly, class:"form-control"}
  - unless readonly
    %br
    = f.submit t('labels.save'), class: 'btn btn-primary'

app/views/students/edit.html.haml
%h3= "#{t('labels.edit')} #{t('activerecord.models.student')}"
%p
  = link_to 'Voltar', students_path, class:"btn btn-info"
%p
  = render 'form', readonly: false

app/views/students/index.html.haml
%h3= "#{t('labels.list')} #{t('activerecord.models.students')}"
%p
  = link_to t('labels.new'), new_student_path, class:"btn btn-primary"

%table.table.table-striped
  %tr
    %th= t('activerecord.attributes.student.name')
    %th= t('activerecord.attributes.student.register_number')
    %th= t('activerecord.attributes.student.status')
    %th
  - @students.each do |student|
    %tr
      %td= student.name
      %td= student.register_number
      %td= student.status_humanize
      %td
        = link_to t('labels.show'), student
        = link_to t('labels.edit'), edit_student_path(student)
        = link_to t('labels.destroy'), student, method: :delete, data: { confirm: "Deseja excluir esse aluno?" }

app/views/students/new.html.haml
%h3= "#{t('labels.new')} #{t('activerecord.models.student')}"
%p
  = link_to 'Voltar', students_path, class:"btn btn-info"
%p
  = render 'form', readonly: false

app/views/students/show.html.haml
%h3= "#{t('labels.show')} #{t('activerecord.models.student')}"
%p
  = link_to 'Voltar', students_path, class:"btn btn-info"
%p
  = render 'form', readonly: true